In [1]:
# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotx

plt.style.use(matplotx.styles.ayu['light'])

In [2]:
# Load Dataset
fm_data = pd.read_csv("fm_data.csv")

fm_data.head()

,Unnamed: 0,Username,Artist,Track,Album,Date,Time
0,0,Babs_05,Isobel Campbell,The Circus Is Leaving Town,Ballad of the Broken Seas,31 Jan 2021,23:36
1,1,Babs_05,Isobel Campbell,Dusty Wreath,Ballad of the Broken Seas,31 Jan 2021,23:32
2,2,Babs_05,Isobel Campbell,Honey Child What Can I Do?,Ballad of the Broken Seas,31 Jan 2021,23:28
3,3,Babs_05,Isobel Campbell,It's Hard To Kill A Bad Thing,Ballad of the Broken Seas,31 Jan 2021,23:25
4,4,Babs_05,Isobel Campbell,Saturday's Gone,Ballad of the Broken Seas,31 Jan 2021,23:21

In [3]:
# Remove unnecessary column
fm_data = fm_data.drop(columns=["Unnamed: 0"])

In [5]:
# Combine Date and Time into one column
fm_data["datetime"] = pd.to_datetime(fm_data["Date"] + " " + fm_data["Time"])
# Extract Hour
fm_data["hour"] = fm_data["datetime"].dt.hour

In [6]:
# Create Time Period Feature
def get_time_period(hour):

    if 5 <= hour < 12:
        return "Morning"

    elif 12 <= hour < 17:
        return "Afternoon"

    elif 17 <= hour < 21:
        return "Evening"

    else:
        return "Night"

fm_data["time_period"] = fm_data["hour"].apply(get_time_period)

In [7]:
# Extract Day of Week
fm_data["day_of_week"] = fm_data["datetime"].dt.day_name()

In [8]:
# Weekend Feature
fm_data["is_weekend"] = fm_data["day_of_week"].isin(["Saturday", "Sunday"])

In [9]:
# Display Final Dataset
fm_data.head()

,Username,Artist,Track,Album,Date,Time,datetime,hour,time_period,day_of_week,is_weekend
0,Babs_05,Isobel Campbell,The Circus Is Leaving Town,Ballad of the Broken Seas,31 Jan 2021,23:36,2021-01-31 23:36:00,23,Night,Sunday,True
1,Babs_05,Isobel Campbell,Dusty Wreath,Ballad of the Broken Seas,31 Jan 2021,23:32,2021-01-31 23:32:00,23,Night,Sunday,True
2,Babs_05,Isobel Campbell,Honey Child What Can I Do?,Ballad of the Broken Seas,31 Jan 2021,23:28,2021-01-31 23:28:00,23,Night,Sunday,True
3,Babs_05,Isobel Campbell,It's Hard To Kill A Bad Thing,Ballad of the Broken Seas,31 Jan 2021,23:25,2021-01-31 23:25:00,23,Night,Sunday,True
4,Babs_05,Isobel Campbell,Saturday's Gone,Ballad of the Broken Seas,31 Jan 2021,23:21,2021-01-31 23:21:00,23,Night,Sunday,True

In [10]:
fm_data[["datetime","time_period","day_of_week","is_weekend"]].head(10)

             datetime time_period day_of_week  is_weekend
0 2021-01-31 23:36:00       Night      Sunday        True
1 2021-01-31 23:32:00       Night      Sunday        True
2 2021-01-31 23:28:00       Night      Sunday        True
3 2021-01-31 23:25:00       Night      Sunday        True
4 2021-01-31 23:21:00       Night      Sunday        True
5 2021-01-31 23:17:00       Night      Sunday        True
6 2021-01-31 23:14:00       Night      Sunday        True
7 2021-01-31 23:11:00       Night      Sunday        True
8 2021-01-31 23:08:00       Night      Sunday        True
9 2021-01-31 23:04:00       Night      Sunday        True